config/routes.rb
Rails.application.routes.draw do
  get 'admin' => "adminhome#top"

  get "admin/articles" => "adminarticle#index"
  get "admin/articles/new" => "adminarticle#new"
  get "admin/articles/:id" => "adminarticle#show"
  post "admin/articles/create" => "adminarticle#create"
  get "admin/articles/:id/edit" => "adminarticle#edit"
  patch "admin/articles/:id/update", to:"adminarticle#update", as: "admin_articles_update"
  post "admin/articles/:id/destroy" => "adminarticle#destroy"


  get "admin/maxims" => "adminmaxim#index"
  get "admin/maxims/new" => "adminmaxim#new"
  get "admin/maxims/:id" => "adminmaxim#show"


  get "admin/exhibitions" => "adminexhibition#index"
  get "admin/exhibitions/new" => "adminexhibition#new"
  get "admin/exhibitions/:id" => "adminexhibition#show"

  get "admin/schools" => "adminschool#index"
  get "admin/schools/new" => "adminschool#new"
  get "admin/schools/id" => "adminschool#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
end

app/models/maxim.rb
class Maxim < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/adminarticle_controller.rb
class AdminarticleController < ApplicationController
  def index
    @articles =Article.all
  end

  def new
    @article=Article.new
  end

  def show
    @article = Article.find_by(id: params[:id])
  end

  def create
    binding.pry
    @article=Article.new(article_params)
    @article.save
    redirect_to("/admin/articles")

  end

  def edit
    @article =Article.find_by(id:params[:id])
  end

  def update
    @article= Article.find_by(id:params[:id])
    #render json: params
#
#    @article.title = params[:article][:title]
#    @article.category = params[:category]
#    @article.content = params[:content]
    @article.update(article_params)#params[:article])
#    @article.save
    redirect_to("/admin/articles")
  end

  def destroy
    @article = Article.find_by(id:params[:id])
    @article.destroy
    redirect_to("/admin/articles")

  end

  private

  def article_params
    params.require(:article).permit(
      :title,
      :category,
      :content
    )
  end

end

app/controllers/adminexhibition_controller.rb
class AdminexhibitionController < ApplicationController
  def index
  end

  def new

  end

  def show

  end
end

app/controllers/adminhome_controller.rb
class AdminhomeController < ApplicationController
  def top
  end
end

app/controllers/adminmaxim_controller.rb
class AdminmaximController < ApplicationController
  def index
  end

  def new

  end

  def show

  end
end

app/controllers/adminschool_controller.rb
class AdminschoolController < ApplicationController
  def index
  end

  def new

  end

  def show

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/adminarticle_helper.rb
module AdminarticleHelper
end

app/helpers/adminexhibition_helper.rb
module AdminexhibitionHelper
end

app/helpers/adminhome_helper.rb
module AdminhomeHelper
end

app/helpers/adminmaxim_helper.rb
module AdminmaximHelper
end

app/helpers/adminschool_helper.rb
module AdminschoolHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adminarticle/edit.html.erb
<h2>記事編集</h2>

<%= form_for(@article, url: admin_articles_update_path ) do |f| %>

<div>
<%= f.label :タイトル %>
<%= f.text_field :title %>
</div>

<div>
<%= f.label :カテゴリ %>
<%= f.select :category, [["a","a"],["b","b"]] %>
</div>

<div>
<%= f.label :内容 %>
<%= f.text_area :content %>
</div>

<div>
<%= f.submit "記事編集" %>
</div>

<% end %>

app/views/adminarticle/index.html.erb
<div>
  <% @articles.each do |article| %>
  <div>

    <%= article.title %>
    <%= article.category %>
    <%= article.content %>
    <%= article.created_at %>
    <%= link_to("詳細","/admin/articles/#{article.id}") %>
  </div>

  <% end %>
</div>

app/views/adminarticle/new.html.erb
<div>
  <h2>新規記事作成フォーム</h2>
</div>

<%= form_for(@article, url: admin_articles_create_path) do |f| %>
  <div>
  <%= f.label :タイトル %>
  <%= f.text_field :title %>
  </div>

  <div>
  <%= f.label :カテゴリ %>
  <%= f.select :category, [["a","a"],["b","b"]] %>
  </div>

  <div>
  <%= f.label :内容 %>
  <%= f.text_area :content %>
  </div>

  <div>
  <%= f.submit "記事作成" %>
  </div>

<% end %>

app/views/adminarticle/show.html.erb
<div>
  <p>
    タイトル：
  </p>
  <%= @article.title %>
</div>

<div>
  <p>
    カテゴリ：
  </p>
  <%= @article.category %>
</div>

<div>
  <p>
    内容：
  </p>
  <%= @article.content %>
</div>

<div>
  <p>
    作成日時：
  </p>
  <%= @article.created_at %>
</div>

<div>
  <p>
    作成者：
  </p>

</div>

<div>
  <%= link_to("編集","/admin/articles/#{@article.id}/edit") %>
  <%= link_to("削除","/admin/articles/#{@article.id}/destroy",{method:"post"}) %>
  <%= link_to("一覧に戻る","/admin/articles") %>

</div>

app/views/adminexhibition/index.html.erb
<p>
  展示会一覧
</p>

app/views/adminexhibition/new.html.erb
<p>
  展示会作るよ
</p>

app/views/adminhome/top.html.erb
<h1>Adminhome#top</h1>
<p>Find me in app/views/adminhome/top.html.erb</p>

app/views/adminmaxim/index.html.erb
<p>
  ことば一覧
</p>

app/views/adminmaxim/new.html.erb
<p>
  ことば作るよ
</p>

app/views/adminschool/index.html.erb
<p>
  教室一覧
</p>

app/views/adminschool/new.html.erb
<p>
  教室作るよ
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to("管理画面トップ", "/admin") %>
    <%= link_to("記事一覧", "/admin/articles") %>
    <%= link_to("記事新規作成", "/admin/articles/new") %>
    <%= link_to("ことば一覧", "/admin/maxims") %>
    <%= link_to("ことば新規作成", "/admin/maxims/new") %>
    <%= link_to("展示会一覧", "/admin/exhibitions") %>
    <%= link_to("展示会新規作成", "/admin/exhibitions/new") %>
    <%= link_to("教室一覧", "/admin/schools") %>
    <%= link_to("教室新規作成", "/admin/schools/new") %>

    <%= yield %>
  </body>
</html>